# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "Calculating the docker image tag"
        if: github.repository == 'pmauduit/temp-gh-actions'
        id: version
        run: |
         if [ github.ref == 'refs/headers/master'] ; then
            DOCKER_TAG=latest ;
         else
            DOCKER_TAG=$( echo ${{ github.ref }} | cut -d'/' -f3) ;
         fi
         echo ::set-output name=VERSION::$DOCKER_TAG
      - name: "build the container"
        if: github.repository == 'pmauduit/temp-gh-actions'
        run: |
          docker pull nginx:latest
          docker tag nginx:latest dudu/popo:${{ steps.version.outputs.VERSION }}

      - name: "push the container"
        if: github.repository == 'pmauduit/temp-gh-actions'
        run: |
          echo "will push  dudu/popo:${{ steps.version.outputs.VERSION }}"

